require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('../models/Question');
const User = require('../models/User');

const questions = [

  // ── DATA STRUCTURES (20) ─────────────────────────────
  { topic:'Data Structures', difficulty:'Easy',   text:'What is the time complexity of accessing an element in an array by index?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(1)'},{label:'D',text:'O(n²)'}], answer:'C', explanation:'Array access by index is O(1) because memory is contiguous.' },
  { topic:'Data Structures', difficulty:'Easy',   text:'Which data structure follows the LIFO principle?', options:[{label:'A',text:'Queue'},{label:'B',text:'Stack'},{label:'C',text:'Linked List'},{label:'D',text:'Tree'}], answer:'B', explanation:'Stack follows Last In First Out (LIFO).' },
  { topic:'Data Structures', difficulty:'Easy',   text:'Which data structure follows the FIFO principle?', options:[{label:'A',text:'Stack'},{label:'B',text:'Tree'},{label:'C',text:'Queue'},{label:'D',text:'Graph'}], answer:'C', explanation:'Queue follows First In First Out (FIFO).' },
  { topic:'Data Structures', difficulty:'Easy',   text:'What is the maximum number of children a node can have in a binary tree?', options:[{label:'A',text:'1'},{label:'B',text:'2'},{label:'C',text:'3'},{label:'D',text:'Unlimited'}], answer:'B', explanation:'In a binary tree each node has at most 2 children.' },
  { topic:'Data Structures', difficulty:'Easy',   text:'Which of the following is a linear data structure?', options:[{label:'A',text:'Tree'},{label:'B',text:'Graph'},{label:'C',text:'Array'},{label:'D',text:'Heap'}], answer:'C', explanation:'Arrays store elements in a linear sequential order.' },
  { topic:'Data Structures', difficulty:'Easy',   text:'What operation removes an element from the top of a stack?', options:[{label:'A',text:'Enqueue'},{label:'B',text:'Dequeue'},{label:'C',text:'Push'},{label:'D',text:'Pop'}], answer:'D', explanation:'Pop removes the top element from a stack.' },
  { topic:'Data Structures', difficulty:'Medium', text:'What is the time complexity of searching in a balanced BST?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(1)'},{label:'D',text:'O(n log n)'}], answer:'B', explanation:'Balanced BST halves the search space at each step giving O(log n).' },
  { topic:'Data Structures', difficulty:'Medium', text:'Which data structure is used to implement a priority queue efficiently?', options:[{label:'A',text:'Stack'},{label:'B',text:'Array'},{label:'C',text:'Heap'},{label:'D',text:'Linked List'}], answer:'C', explanation:'A heap supports insert and extract-min/max in O(log n).' },
  { topic:'Data Structures', difficulty:'Medium', text:'What is the time complexity of inserting at the beginning of a singly linked list?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(1)'},{label:'D',text:'O(n²)'}], answer:'C', explanation:'Inserting at head only requires updating the head pointer — O(1).' },
  { topic:'Data Structures', difficulty:'Medium', text:'Which traversal of a BST gives elements in sorted order?', options:[{label:'A',text:'Preorder'},{label:'B',text:'Postorder'},{label:'C',text:'Inorder'},{label:'D',text:'Level order'}], answer:'C', explanation:'Inorder traversal (left → root → right) of a BST produces sorted output.' },
  { topic:'Data Structures', difficulty:'Medium', text:'What is the height of a complete binary tree with n nodes?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(n log n)'},{label:'D',text:'O(√n)'}], answer:'B', explanation:'A complete binary tree is nearly balanced so height is O(log n).' },
  { topic:'Data Structures', difficulty:'Medium', text:'In a min-heap, what is true about the root node?', options:[{label:'A',text:'It is the largest element'},{label:'B',text:'It is the smallest element'},{label:'C',text:'It is the median element'},{label:'D',text:'It can be any element'}], answer:'B', explanation:'In a min-heap the root always holds the minimum value.' },
  { topic:'Data Structures', difficulty:'Medium', text:'What is the amortized time complexity of pushing to a dynamic array?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(1)'},{label:'D',text:'O(n²)'}], answer:'C', explanation:'Although resizing is O(n) occasionally, amortized cost per push is O(1).' },
  { topic:'Data Structures', difficulty:'Hard',   text:'What is the worst-case time complexity of inserting into a hash table?', options:[{label:'A',text:'O(1)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(n)'},{label:'D',text:'O(n log n)'}], answer:'C', explanation:'In worst case all keys collide in one bucket making lookup O(n).' },
  { topic:'Data Structures', difficulty:'Hard',   text:'Which data structure allows O(1) insertion and O(log n) retrieval of the minimum?', options:[{label:'A',text:'Sorted array'},{label:'B',text:'Min-heap'},{label:'C',text:'Hash table'},{label:'D',text:'AVL tree'}], answer:'B', explanation:'Min-heap inserts in O(log n) and retrieves min in O(1).' },
  { topic:'Data Structures', difficulty:'Hard',   text:'What differentiates an AVL tree from a regular BST?', options:[{label:'A',text:'AVL allows duplicate keys'},{label:'B',text:'AVL is self-balancing with height difference ≤ 1'},{label:'C',text:'AVL uses hashing'},{label:'D',text:'AVL stores data only in leaves'}], answer:'B', explanation:'AVL trees maintain balance factor of -1, 0, or 1 at every node.' },
  { topic:'Data Structures', difficulty:'Hard',   text:'What is the time complexity of building a heap from an unsorted array?', options:[{label:'A',text:'O(n log n)'},{label:'B',text:'O(n²)'},{label:'C',text:'O(n)'},{label:'D',text:'O(log n)'}], answer:'C', explanation:'Heapify-down applied bottom-up runs in O(n) total time.' },
  { topic:'Data Structures', difficulty:'Hard',   text:'Which of the following is true about a B-tree of order m?', options:[{label:'A',text:'Every node has exactly m children'},{label:'B',text:'Each node has at most m children and at least ⌈m/2⌉'},{label:'C',text:'Only leaf nodes store data'},{label:'D',text:'B-tree is always a complete binary tree'}], answer:'B', explanation:'B-tree nodes have between ⌈m/2⌉ and m children to stay balanced.' },
  { topic:'Data Structures', difficulty:'Hard',   text:'What is the space complexity of DFS on a graph with V vertices and E edges?', options:[{label:'A',text:'O(V+E)'},{label:'B',text:'O(V)'},{label:'C',text:'O(E)'},{label:'D',text:'O(1)'}], answer:'B', explanation:'DFS uses a stack of at most V frames for the recursion call stack.' },
  { topic:'Data Structures', difficulty:'Hard',   text:'In a doubly linked list, what is the time complexity of deleting a node given its pointer?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(1)'},{label:'D',text:'O(n²)'}], answer:'C', explanation:'With a pointer to the node, deletion only updates prev and next pointers — O(1).' },

  // ── ALGORITHMS (20) ──────────────────────────────────
  { topic:'Algorithms', difficulty:'Easy',   text:'What is the time complexity of bubble sort in the worst case?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(n log n)'},{label:'C',text:'O(n²)'},{label:'D',text:'O(log n)'}], answer:'C', explanation:'Bubble sort compares each pair n times giving O(n²).' },
  { topic:'Algorithms', difficulty:'Easy',   text:'Which algorithm finds the shortest path in an unweighted graph?', options:[{label:'A',text:'DFS'},{label:'B',text:'BFS'},{label:'C',text:'Dijkstra'},{label:'D',text:'Bellman-Ford'}], answer:'B', explanation:'BFS explores level by level so finds shortest unweighted path.' },
  { topic:'Algorithms', difficulty:'Easy',   text:'What is the best-case time complexity of insertion sort?', options:[{label:'A',text:'O(n²)'},{label:'B',text:'O(n log n)'},{label:'C',text:'O(n)'},{label:'D',text:'O(1)'}], answer:'C', explanation:'Insertion sort is O(n) when the array is already sorted.' },
  { topic:'Algorithms', difficulty:'Easy',   text:'Binary search requires the array to be:', options:[{label:'A',text:'Unsorted'},{label:'B',text:'Sorted'},{label:'C',text:'Filled with unique elements'},{label:'D',text:'Of even length'}], answer:'B', explanation:'Binary search only works correctly on sorted arrays.' },
  { topic:'Algorithms', difficulty:'Easy',   text:'What is the time complexity of linear search?', options:[{label:'A',text:'O(1)'},{label:'B',text:'O(log n)'},{label:'C',text:'O(n)'},{label:'D',text:'O(n²)'}], answer:'C', explanation:'Linear search checks each element one by one — O(n).' },
  { topic:'Algorithms', difficulty:'Easy',   text:'Which sorting algorithm is stable and has O(n log n) worst-case complexity?', options:[{label:'A',text:'Quick sort'},{label:'B',text:'Heap sort'},{label:'C',text:'Merge sort'},{label:'D',text:'Selection sort'}], answer:'C', explanation:'Merge sort is stable and always O(n log n).' },
  { topic:'Algorithms', difficulty:'Medium', text:'What is the recurrence relation for merge sort?', options:[{label:'A',text:'T(n) = T(n-1) + O(n)'},{label:'B',text:'T(n) = 2T(n/2) + O(n)'},{label:'C',text:'T(n) = T(n/2) + O(1)'},{label:'D',text:'T(n) = 2T(n-1) + O(1)'}], answer:'B', explanation:'Merge sort splits into 2 halves and merges in O(n).' },
  { topic:'Algorithms', difficulty:'Medium', text:'Which paradigm does dynamic programming primarily use?', options:[{label:'A',text:'Divide and Conquer'},{label:'B',text:'Greedy'},{label:'C',text:'Memoization of overlapping subproblems'},{label:'D',text:'Backtracking'}], answer:'C', explanation:'DP solves overlapping subproblems and stores results to avoid recomputation.' },
  { topic:'Algorithms', difficulty:'Medium', text:'What is the average time complexity of quicksort?', options:[{label:'A',text:'O(n²)'},{label:'B',text:'O(n)'},{label:'C',text:'O(n log n)'},{label:'D',text:'O(log n)'}], answer:'C', explanation:'With good pivot selection quicksort averages O(n log n).' },
  { topic:'Algorithms', difficulty:'Medium', text:'Which algorithm is used to detect a cycle in a directed graph?', options:[{label:'A',text:'BFS'},{label:'B',text:'DFS with coloring'},{label:'C',text:'Dijkstra'},{label:'D',text:'Prim\'s'}], answer:'B', explanation:'DFS with white/gray/black coloring detects back edges which indicate cycles.' },
  { topic:'Algorithms', difficulty:'Medium', text:'What is the greedy choice in Kruskal\'s MST algorithm?', options:[{label:'A',text:'Pick the edge with maximum weight'},{label:'B',text:'Pick the edge with minimum weight that does not form a cycle'},{label:'C',text:'Pick edges from a single vertex'},{label:'D',text:'Pick edges randomly'}], answer:'B', explanation:'Kruskal\'s always picks the lightest edge that doesn\'t create a cycle.' },
  { topic:'Algorithms', difficulty:'Medium', text:'What does the Master Theorem solve?', options:[{label:'A',text:'Graph shortest paths'},{label:'B',text:'Recurrence relations of divide-and-conquer algorithms'},{label:'C',text:'Sorting lower bounds'},{label:'D',text:'Dynamic programming tables'}], answer:'B', explanation:'Master Theorem gives asymptotic solutions to T(n)=aT(n/b)+f(n).' },
  { topic:'Algorithms', difficulty:'Medium', text:'Which algorithm solves the 0/1 knapsack problem optimally?', options:[{label:'A',text:'Greedy'},{label:'B',text:'BFS'},{label:'C',text:'Dynamic Programming'},{label:'D',text:'Binary Search'}], answer:'C', explanation:'0/1 knapsack has overlapping subproblems solved optimally by DP.' },
  { topic:'Algorithms', difficulty:'Hard',   text:'What is the time complexity of Dijkstra\'s algorithm using a min-heap?', options:[{label:'A',text:'O(V²)'},{label:'B',text:'O(E log V)'},{label:'C',text:'O(VE)'},{label:'D',text:'O(V log E)'}], answer:'B', explanation:'Each edge relaxation costs O(log V) with a min-heap priority queue.' },
  { topic:'Algorithms', difficulty:'Hard',   text:'Which algorithm can handle negative weight edges in shortest path?', options:[{label:'A',text:'Dijkstra'},{label:'B',text:'BFS'},{label:'C',text:'Bellman-Ford'},{label:'D',text:'Prim\'s'}], answer:'C', explanation:'Bellman-Ford relaxes all edges V-1 times and handles negative weights.' },
  { topic:'Algorithms', difficulty:'Hard',   text:'What is the time complexity of the Floyd-Warshall algorithm?', options:[{label:'A',text:'O(V²)'},{label:'B',text:'O(V³)'},{label:'C',text:'O(VE)'},{label:'D',text:'O(E log V)'}], answer:'B', explanation:'Floyd-Warshall uses three nested loops over V vertices — O(V³).' },
  { topic:'Algorithms', difficulty:'Hard',   text:'What is the lower bound for comparison-based sorting algorithms?', options:[{label:'A',text:'O(n)'},{label:'B',text:'O(n log n)'},{label:'C',text:'O(n²)'},{label:'D',text:'O(log n)'}], answer:'B', explanation:'Decision tree argument proves Ω(n log n) lower bound for comparison sorts.' },
  { topic:'Algorithms', difficulty:'Hard',   text:'Which technique does the KMP string matching algorithm use?', options:[{label:'A',text:'Hashing'},{label:'B',text:'Dynamic programming failure function'},{label:'C',text:'Divide and conquer'},{label:'D',text:'Backtracking'}], answer:'B', explanation:'KMP precomputes a failure function to avoid redundant comparisons.' },
  { topic:'Algorithms', difficulty:'Hard',   text:'What is the time complexity of Topological Sort using DFS?', options:[{label:'A',text:'O(V²)'},{label:'B',text:'O(V log V)'},{label:'C',text:'O(V + E)'},{label:'D',text:'O(E log V)'}], answer:'C', explanation:'DFS visits each vertex and edge once giving O(V+E).' },
  { topic:'Algorithms', difficulty:'Hard',   text:'Which problem is solved by the Hungarian algorithm?', options:[{label:'A',text:'Shortest path'},{label:'B',text:'Minimum spanning tree'},{label:'C',text:'Assignment problem'},{label:'D',text:'Maximum flow'}], answer:'C', explanation:'The Hungarian algorithm solves the assignment problem in O(n³).' },

  // ── DBMS (20) ────────────────────────────────────────
  { topic:'DBMS', difficulty:'Easy',   text:'What does SQL stand for?', options:[{label:'A',text:'Structured Query Language'},{label:'B',text:'Simple Query Language'},{label:'C',text:'Standard Query Logic'},{label:'D',text:'Sequential Query Language'}], answer:'A', explanation:'SQL = Structured Query Language used to manage relational databases.' },
  { topic:'DBMS', difficulty:'Easy',   text:'Which SQL command is used to retrieve data from a table?', options:[{label:'A',text:'INSERT'},{label:'B',text:'UPDATE'},{label:'C',text:'SELECT'},{label:'D',text:'DELETE'}], answer:'C', explanation:'SELECT retrieves data from one or more tables.' },
  { topic:'DBMS', difficulty:'Easy',   text:'Which constraint ensures no duplicate values in a column?', options:[{label:'A',text:'NOT NULL'},{label:'B',text:'FOREIGN KEY'},{label:'C',text:'CHECK'},{label:'D',text:'UNIQUE'}], answer:'D', explanation:'UNIQUE constraint prevents duplicate values in a column.' },
  { topic:'DBMS', difficulty:'Easy',   text:'What is a primary key?', options:[{label:'A',text:'A key that can have NULL values'},{label:'B',text:'A key that uniquely identifies each row in a table'},{label:'C',text:'A key that references another table'},{label:'D',text:'A key used for sorting'}], answer:'B', explanation:'Primary key uniquely identifies each record and cannot be NULL.' },
  { topic:'DBMS', difficulty:'Easy',   text:'Which normal form eliminates partial functional dependencies?', options:[{label:'A',text:'1NF'},{label:'B',text:'2NF'},{label:'C',text:'3NF'},{label:'D',text:'BCNF'}], answer:'B', explanation:'2NF removes partial dependencies on composite primary keys.' },
  { topic:'DBMS', difficulty:'Easy',   text:'What does ACID stand for in database transactions?', options:[{label:'A',text:'Atomicity, Consistency, Isolation, Durability'},{label:'B',text:'Array, Cursor, Index, Data'},{label:'C',text:'Access, Control, Integrity, Definition'},{label:'D',text:'Atomicity, Concurrency, Isolation, Distribution'}], answer:'A', explanation:'ACID properties ensure reliable database transactions.' },
  { topic:'DBMS', difficulty:'Medium', text:'Which join returns all rows from both tables including non-matching rows?', options:[{label:'A',text:'INNER JOIN'},{label:'B',text:'LEFT JOIN'},{label:'C',text:'RIGHT JOIN'},{label:'D',text:'FULL OUTER JOIN'}], answer:'D', explanation:'FULL OUTER JOIN includes all rows from both tables, nulls for no match.' },
  { topic:'DBMS', difficulty:'Medium', text:'What is a foreign key?', options:[{label:'A',text:'Primary key of the same table'},{label:'B',text:'A key that references the primary key of another table'},{label:'C',text:'A unique key'},{label:'D',text:'An indexed column'}], answer:'B', explanation:'Foreign key enforces referential integrity between two tables.' },
  { topic:'DBMS', difficulty:'Medium', text:'What is the difference between DELETE and TRUNCATE?', options:[{label:'A',text:'No difference'},{label:'B',text:'DELETE removes specific rows and is logged; TRUNCATE removes all rows faster'},{label:'C',text:'TRUNCATE can have a WHERE clause'},{label:'D',text:'DELETE is DDL; TRUNCATE is DML'}], answer:'B', explanation:'DELETE is DML with WHERE support; TRUNCATE is DDL and faster.' },
  { topic:'DBMS', difficulty:'Medium', text:'What is an index in a database?', options:[{label:'A',text:'A copy of the entire table'},{label:'B',text:'A data structure that speeds up data retrieval'},{label:'C',text:'A constraint that prevents duplicates'},{label:'D',text:'A stored procedure'}], answer:'B', explanation:'Indexes allow faster lookups at the cost of additional storage.' },
  { topic:'DBMS', difficulty:'Medium', text:'What is a view in SQL?', options:[{label:'A',text:'A physical copy of a table'},{label:'B',text:'A virtual table based on a SELECT query'},{label:'C',text:'A stored procedure'},{label:'D',text:'An index on a table'}], answer:'B', explanation:'A view is a named query stored in the database as a virtual table.' },
  { topic:'DBMS', difficulty:'Medium', text:'Which isolation level prevents dirty reads but allows non-repeatable reads?', options:[{label:'A',text:'Read Uncommitted'},{label:'B',text:'Read Committed'},{label:'C',text:'Repeatable Read'},{label:'D',text:'Serializable'}], answer:'B', explanation:'Read Committed prevents dirty reads but allows non-repeatable reads.' },
  { topic:'DBMS', difficulty:'Medium', text:'What is denormalization?', options:[{label:'A',text:'Converting to higher normal form'},{label:'B',text:'Intentionally adding redundancy to improve read performance'},{label:'C',text:'Removing all foreign keys'},{label:'D',text:'Splitting a table into smaller ones'}], answer:'B', explanation:'Denormalization trades storage for faster reads by adding redundant data.' },
  { topic:'DBMS', difficulty:'Hard',   text:'What is a deadlock in DBMS and how can it be prevented?', options:[{label:'A',text:'Two transactions waiting for each other; prevented by timeout or wait-die'},{label:'B',text:'A transaction holding all locks; prevented by rollback'},{label:'C',text:'A corrupted index; prevented by reindexing'},{label:'D',text:'A slow query; prevented by caching'}], answer:'A', explanation:'Deadlock is circular wait between transactions; timeout or ordering prevents it.' },
  { topic:'DBMS', difficulty:'Hard',   text:'What is the difference between 3NF and BCNF?', options:[{label:'A',text:'No difference'},{label:'B',text:'BCNF is stricter — every determinant must be a superkey'},{label:'C',text:'3NF allows more redundancy than BCNF and BCNF is easier to achieve'},{label:'D',text:'3NF is stricter than BCNF'}], answer:'B', explanation:'BCNF requires every determinant to be a superkey, stricter than 3NF.' },
  { topic:'DBMS', difficulty:'Hard',   text:'What does a clustered index do?', options:[{label:'A',text:'Creates a separate index table'},{label:'B',text:'Physically reorders the table data to match the index'},{label:'C',text:'Indexes all columns at once'},{label:'D',text:'Speeds up only JOIN operations'}], answer:'B', explanation:'Clustered index sorts and stores the data rows based on the key.' },
  { topic:'DBMS', difficulty:'Hard',   text:'What is the purpose of the two-phase locking (2PL) protocol?', options:[{label:'A',text:'To speed up transactions'},{label:'B',text:'To ensure serializability of transactions'},{label:'C',text:'To prevent disk failures'},{label:'D',text:'To enable parallel writes'}], answer:'B', explanation:'2PL guarantees serializability by acquiring all locks before releasing any.' },
  { topic:'DBMS', difficulty:'Hard',   text:'What is a transaction log used for?', options:[{label:'A',text:'Storing user passwords'},{label:'B',text:'Recovery from failures using redo and undo operations'},{label:'C',text:'Speeding up SELECT queries'},{label:'D',text:'Caching frequently accessed data'}], answer:'B', explanation:'Transaction logs record changes enabling crash recovery via redo/undo.' },
  { topic:'DBMS', difficulty:'Hard',   text:'What is phantom read in database transactions?', options:[{label:'A',text:'Reading uncommitted data from another transaction'},{label:'B',text:'Reading the same row twice getting different values'},{label:'C',text:'New rows appearing in a repeated query due to another transaction inserting'},{label:'D',text:'A transaction reading its own uncommitted data'}], answer:'C', explanation:'Phantom reads occur when new rows are inserted by another transaction between two reads.' },
  { topic:'DBMS', difficulty:'Hard',   text:'Which data model does MongoDB use?', options:[{label:'A',text:'Relational'},{label:'B',text:'Document-oriented'},{label:'C',text:'Column-family'},{label:'D',text:'Graph'}], answer:'B', explanation:'MongoDB stores data as BSON documents in a document-oriented model.' },

  // ── COMPUTER NETWORKS (20) ────────────────────────────
  { topic:'Computer Networks', difficulty:'Easy',   text:'Which layer of the OSI model is responsible for routing?', options:[{label:'A',text:'Data Link'},{label:'B',text:'Transport'},{label:'C',text:'Network'},{label:'D',text:'Session'}], answer:'C', explanation:'The Network layer handles routing packets using IP addresses.' },
  { topic:'Computer Networks', difficulty:'Easy',   text:'What does HTTP stand for?', options:[{label:'A',text:'HyperText Transfer Protocol'},{label:'B',text:'High Transfer Text Protocol'},{label:'C',text:'Hyperlink Text Transfer Process'},{label:'D',text:'Host Transfer Protocol'}], answer:'A', explanation:'HTTP = HyperText Transfer Protocol, used for web communication.' },
  { topic:'Computer Networks', difficulty:'Easy',   text:'What is the purpose of DNS?', options:[{label:'A',text:'Encrypt network traffic'},{label:'B',text:'Assign IP addresses dynamically'},{label:'C',text:'Translate domain names to IP addresses'},{label:'D',text:'Manage MAC addresses'}], answer:'C', explanation:'DNS resolves human-readable domain names to IP addresses.' },
  { topic:'Computer Networks', difficulty:'Easy',   text:'Which protocol is used to send emails?', options:[{label:'A',text:'FTP'},{label:'B',text:'HTTP'},{label:'C',text:'SMTP'},{label:'D',text:'SSH'}], answer:'C', explanation:'SMTP (Simple Mail Transfer Protocol) is used to send emails.' },
  { topic:'Computer Networks', difficulty:'Easy',   text:'How many layers does the OSI model have?', options:[{label:'A',text:'4'},{label:'B',text:'5'},{label:'C',text:'6'},{label:'D',text:'7'}], answer:'D', explanation:'The OSI model has 7 layers from Physical to Application.' },
  { topic:'Computer Networks', difficulty:'Easy',   text:'What is the default port number for HTTPS?', options:[{label:'A',text:'80'},{label:'B',text:'21'},{label:'C',text:'443'},{label:'D',text:'22'}], answer:'C', explanation:'HTTPS uses port 443 by default.' },
  { topic:'Computer Networks', difficulty:'Medium', text:'What is the difference between TCP and UDP?', options:[{label:'A',text:'TCP is faster; UDP is reliable'},{label:'B',text:'TCP is connection-oriented and reliable; UDP is connectionless and faster'},{label:'C',text:'TCP uses IP; UDP does not'},{label:'D',text:'TCP is for video; UDP is for web'}], answer:'B', explanation:'TCP guarantees delivery with handshaking; UDP is faster but unreliable.' },
  { topic:'Computer Networks', difficulty:'Medium', text:'What is the purpose of ARP?', options:[{label:'A',text:'Resolve domain names to IPs'},{label:'B',text:'Map IP addresses to MAC addresses'},{label:'C',text:'Assign IP addresses dynamically'},{label:'D',text:'Encrypt network packets'}], answer:'B', explanation:'ARP (Address Resolution Protocol) maps IP to MAC on a LAN.' },
  { topic:'Computer Networks', difficulty:'Medium', text:'What is subnetting?', options:[{label:'A',text:'Connecting two different networks'},{label:'B',text:'Dividing a network into smaller sub-networks'},{label:'C',text:'Encrypting network traffic'},{label:'D',text:'Assigning MAC addresses'}], answer:'B', explanation:'Subnetting divides a large network into smaller manageable sub-networks.' },
  { topic:'Computer Networks', difficulty:'Medium', text:'Which protocol dynamically assigns IP addresses to devices?', options:[{label:'A',text:'DNS'},{label:'B',text:'ARP'},{label:'C',text:'DHCP'},{label:'D',text:'FTP'}], answer:'C', explanation:'DHCP automatically assigns IP addresses, subnet masks, and gateways.' },
  { topic:'Computer Networks', difficulty:'Medium', text:'What is the role of the MAC address?', options:[{label:'A',text:'Identify a device on the internet'},{label:'B',text:'Identify a device on a local network at the Data Link layer'},{label:'C',text:'Route packets between networks'},{label:'D',text:'Encrypt data in transit'}], answer:'B', explanation:'MAC address uniquely identifies a network interface on a local network.' },
  { topic:'Computer Networks', difficulty:'Medium', text:'What is a firewall?', options:[{label:'A',text:'A device that speeds up internet connection'},{label:'B',text:'A security system that monitors and controls network traffic'},{label:'C',text:'A protocol for encrypting data'},{label:'D',text:'A type of network cable'}], answer:'B', explanation:'A firewall filters incoming and outgoing traffic based on security rules.' },
  { topic:'Computer Networks', difficulty:'Medium', text:'What is the difference between a hub and a switch?', options:[{label:'A',text:'No difference'},{label:'B',text:'Hub broadcasts to all ports; switch forwards to specific port using MAC'},{label:'C',text:'Switch broadcasts to all; hub is selective'},{label:'D',text:'Hub works at Layer 3; switch at Layer 2'}], answer:'B', explanation:'Switches use MAC address tables to forward frames selectively, unlike hubs.' },
  { topic:'Computer Networks', difficulty:'Hard',   text:'What is the TCP three-way handshake sequence?', options:[{label:'A',text:'SYN → ACK → SYN-ACK'},{label:'B',text:'SYN → SYN-ACK → ACK'},{label:'C',text:'ACK → SYN → SYN-ACK'},{label:'D',text:'SYN-ACK → SYN → ACK'}], answer:'B', explanation:'Client sends SYN, server replies SYN-ACK, client confirms with ACK.' },
  { topic:'Computer Networks', difficulty:'Hard',   text:'What is the purpose of HTTPS over HTTP?', options:[{label:'A',text:'Faster data transfer'},{label:'B',text:'Encryption of data using TLS/SSL'},{label:'C',text:'Supports more HTTP methods'},{label:'D',text:'Uses UDP instead of TCP'}], answer:'B', explanation:'HTTPS encrypts communication using TLS/SSL preventing eavesdropping.' },
  { topic:'Computer Networks', difficulty:'Hard',   text:'What is BGP used for?', options:[{label:'A',text:'Assign IP addresses within a LAN'},{label:'B',text:'Route packets between autonomous systems on the internet'},{label:'C',text:'Encrypt network traffic'},{label:'D',text:'Manage domain names'}], answer:'B', explanation:'BGP (Border Gateway Protocol) is the routing protocol of the internet.' },
  { topic:'Computer Networks', difficulty:'Hard',   text:'What is the sliding window protocol used for?', options:[{label:'A',text:'Encrypting data in transit'},{label:'B',text:'Flow control and reliable transmission in TCP'},{label:'C',text:'Assigning IP addresses'},{label:'D',text:'Resolving MAC to IP'}], answer:'B', explanation:'Sliding window allows multiple frames to be sent before needing acknowledgment.' },
  { topic:'Computer Networks', difficulty:'Hard',   text:'What is NAT and why is it used?', options:[{label:'A',text:'Network Address Translation; maps private IPs to a public IP'},{label:'B',text:'Node Access Table; manages MAC addresses'},{label:'C',text:'Network Authentication Token; secures login'},{label:'D',text:'Null Address Transfer; discards packets'}], answer:'A', explanation:'NAT translates private IPs to public IPs allowing multiple devices to share one IP.' },
  { topic:'Computer Networks', difficulty:'Hard',   text:'What is the difference between IPv4 and IPv6?', options:[{label:'A',text:'IPv6 is older; IPv4 is newer'},{label:'B',text:'IPv4 uses 32-bit addresses; IPv6 uses 128-bit providing far more addresses'},{label:'C',text:'IPv4 supports encryption; IPv6 does not'},{label:'D',text:'No significant difference'}], answer:'B', explanation:'IPv4 has ~4 billion addresses; IPv6 has 340 undecillion solving exhaustion.' },
  { topic:'Computer Networks', difficulty:'Hard',   text:'In TCP congestion control, what happens when a timeout occurs?', options:[{label:'A',text:'Window size doubles'},{label:'B',text:'Connection is dropped'},{label:'C',text:'Slow start threshold is halved and cwnd resets to 1'},{label:'D',text:'Window size stays the same'}], answer:'C', explanation:'On timeout, ssthresh = cwnd/2 and congestion window resets to 1 MSS.' },

  // ── OS (20) ──────────────────────────────────────────
  { topic:'OS', difficulty:'Easy',   text:'What is a process in an operating system?', options:[{label:'A',text:'A program stored on disk'},{label:'B',text:'A program in execution'},{label:'C',text:'A file in memory'},{label:'D',text:'A hardware component'}], answer:'B', explanation:'A process is a program that is currently being executed by the CPU.' },
  { topic:'OS', difficulty:'Easy',   text:'Which scheduling algorithm gives priority to the shortest job?', options:[{label:'A',text:'FCFS'},{label:'B',text:'Round Robin'},{label:'C',text:'SJF'},{label:'D',text:'Priority Scheduling'}], answer:'C', explanation:'Shortest Job First picks the process with the smallest burst time.' },
  { topic:'OS', difficulty:'Easy',   text:'What is a deadlock?', options:[{label:'A',text:'A process using 100% CPU'},{label:'B',text:'A set of processes blocked waiting for each other indefinitely'},{label:'C',text:'A memory leak in a process'},{label:'D',text:'An OS crash'}], answer:'B', explanation:'Deadlock occurs when processes are circularly waiting for resources.' },
  { topic:'OS', difficulty:'Easy',   text:'What does CPU scheduling determine?', options:[{label:'A',text:'Which process gets the CPU and for how long'},{label:'B',text:'How memory is allocated to processes'},{label:'C',text:'Which files a process can access'},{label:'D',text:'How I/O devices are managed'}], answer:'A', explanation:'CPU scheduler selects which ready process gets CPU time.' },
  { topic:'OS', difficulty:'Easy',   text:'What is virtual memory?', options:[{label:'A',text:'Extra physical RAM installed in a computer'},{label:'B',text:'An abstraction that gives processes the illusion of large contiguous memory'},{label:'C',text:'Memory used only by the kernel'},{label:'D',text:'Cache memory on the CPU'}], answer:'B', explanation:'Virtual memory uses disk space to extend apparent RAM available to processes.' },
  { topic:'OS', difficulty:'Easy',   text:'Which of the following is NOT a state of a process?', options:[{label:'A',text:'Running'},{label:'B',text:'Ready'},{label:'C',text:'Sleeping'},{label:'D',text:'Compiling'}], answer:'D', explanation:'Process states are New, Ready, Running, Waiting, and Terminated — not Compiling.' },
  { topic:'OS', difficulty:'Medium', text:'What is thrashing in operating systems?', options:[{label:'A',text:'Excessive CPU usage'},{label:'B',text:'Excessive paging causing low CPU utilization'},{label:'C',text:'Deadlock between processes'},{label:'D',text:'Memory corruption'}], answer:'B', explanation:'Thrashing happens when processes spend more time paging than executing.' },
  { topic:'OS', difficulty:'Medium', text:'What is the difference between a process and a thread?', options:[{label:'A',text:'No difference'},{label:'B',text:'Thread is heavier than a process'},{label:'C',text:'Threads share the same address space; processes have separate memory'},{label:'D',text:'Processes share memory; threads do not'}], answer:'C', explanation:'Threads within a process share code, data, and heap but have separate stacks.' },
  { topic:'OS', difficulty:'Medium', text:'What is a semaphore used for?', options:[{label:'A',text:'Memory allocation'},{label:'B',text:'Process synchronization and mutual exclusion'},{label:'C',text:'CPU scheduling'},{label:'D',text:'File management'}], answer:'B', explanation:'Semaphores are synchronization primitives controlling access to shared resources.' },
  { topic:'OS', difficulty:'Medium', text:'What is the purpose of the page table in an OS?', options:[{label:'A',text:'Store process priority'},{label:'B',text:'Map virtual addresses to physical addresses'},{label:'C',text:'Schedule processes'},{label:'D',text:'Manage file permissions'}], answer:'B', explanation:'Page table translates virtual page numbers to physical frame numbers.' },
  { topic:'OS', difficulty:'Medium', text:'What is a context switch?', options:[{label:'A',text:'Switching between user and kernel mode'},{label:'B',text:'Saving the state of one process and loading another'},{label:'C',text:'Changing the CPU clock speed'},{label:'D',text:'Switching between different file systems'}], answer:'B', explanation:'Context switch saves current process state and restores the next process.' },
  { topic:'OS', difficulty:'Medium', text:'What is the difference between preemptive and non-preemptive scheduling?', options:[{label:'A',text:'No difference'},{label:'B',text:'Preemptive can interrupt a running process; non-preemptive waits for it to finish'},{label:'C',text:'Non-preemptive is faster'},{label:'D',text:'Preemptive only works on multi-core CPUs'}], answer:'B', explanation:'Preemptive scheduling can forcibly remove CPU from a running process.' },
  { topic:'OS', difficulty:'Medium', text:'What is internal fragmentation?', options:[{label:'A',text:'Free memory scattered in small blocks between allocations'},{label:'B',text:'Wasted memory inside an allocated block due to fixed partition sizes'},{label:'C',text:'A corrupted memory region'},{label:'D',text:'Memory used by the kernel'}], answer:'B', explanation:'Internal fragmentation is unused space within an allocated memory block.' },
  { topic:'OS', difficulty:'Hard',   text:'Which page replacement algorithm suffers from Belady\'s anomaly?', options:[{label:'A',text:'LRU'},{label:'B',text:'Optimal'},{label:'C',text:'FIFO'},{label:'D',text:'LFU'}], answer:'C', explanation:'FIFO can have MORE page faults with more frames — this is Belady\'s anomaly.' },
  { topic:'OS', difficulty:'Hard',   text:'What are the four necessary conditions for deadlock?', options:[{label:'A',text:'Mutual exclusion, Hold and wait, No preemption, Circular wait'},{label:'B',text:'Starvation, Aging, Priority inversion, Livelock'},{label:'C',text:'Paging, Segmentation, Swapping, Fragmentation'},{label:'D',text:'Busy wait, Spinlock, Mutex, Semaphore'}], answer:'A', explanation:'Coffman conditions: Mutual exclusion + Hold and wait + No preemption + Circular wait.' },
  { topic:'OS', difficulty:'Hard',   text:'What is the Banker\'s algorithm used for?', options:[{label:'A',text:'CPU scheduling'},{label:'B',text:'Deadlock avoidance by checking safe state before granting resources'},{label:'C',text:'Memory allocation using paging'},{label:'D',text:'File system management'}], answer:'B', explanation:'Banker\'s algorithm checks if granting a resource leads to a safe state.' },
  { topic:'OS', difficulty:'Hard',   text:'What is the difference between a mutex and a semaphore?', options:[{label:'A',text:'No difference'},{label:'B',text:'Mutex is binary and owned by one thread; semaphore can count and be signaled by any thread'},{label:'C',text:'Semaphore is binary; mutex can count'},{label:'D',text:'Mutex is used only in kernel mode'}], answer:'B', explanation:'Mutex has ownership semantics; semaphore is a general signaling mechanism.' },
  { topic:'OS', difficulty:'Hard',   text:'What is copy-on-write (COW) in operating systems?', options:[{label:'A',text:'Copying files on write to disk'},{label:'B',text:'Sharing memory pages between processes until one writes, then copying'},{label:'C',text:'Writing data twice for redundancy'},{label:'D',text:'A file compression technique'}], answer:'B', explanation:'COW defers copying shared memory until a write occurs, saving resources.' },
  { topic:'OS', difficulty:'Hard',   text:'What is the purpose of the Translation Lookaside Buffer (TLB)?', options:[{label:'A',text:'Store recently used disk blocks'},{label:'B',text:'Cache recent virtual-to-physical address translations'},{label:'C',text:'Buffer CPU instructions'},{label:'D',text:'Store page table entries on disk'}], answer:'B', explanation:'TLB is a fast cache for page table lookups reducing memory access time.' },
  { topic:'OS', difficulty:'Hard',   text:'What is priority inversion and how is it solved?', options:[{label:'A',text:'High-priority task is blocked by a lower-priority one; solved by priority inheritance'},{label:'B',text:'Two tasks with same priority running together; solved by round robin'},{label:'C',text:'A task losing its priority over time; solved by aging'},{label:'D',text:'Kernel preempting user tasks; solved by disabling interrupts'}], answer:'A', explanation:'Priority inheritance temporarily boosts the low-priority task\'s priority to resolve inversion.' },

  // ── AI & ML (20) ─────────────────────────────────────
  { topic:'AI & ML', difficulty:'Easy',   text:'What is supervised learning?', options:[{label:'A',text:'Learning without any data'},{label:'B',text:'Learning from labeled training data'},{label:'C',text:'Learning by rewards and penalties'},{label:'D',text:'Learning from unlabeled data'}], answer:'B', explanation:'Supervised learning uses labeled input-output pairs to train a model.' },
  { topic:'AI & ML', difficulty:'Easy',   text:'Which of the following is a classification algorithm?', options:[{label:'A',text:'Linear Regression'},{label:'B',text:'K-Means'},{label:'C',text:'Decision Tree'},{label:'D',text:'PCA'}], answer:'C', explanation:'Decision Tree is used for both classification and regression tasks.' },
  { topic:'AI & ML', difficulty:'Easy',   text:'What is unsupervised learning?', options:[{label:'A',text:'Learning with labeled data'},{label:'B',text:'Learning patterns from unlabeled data'},{label:'C',text:'Learning from human feedback'},{label:'D',text:'Learning using reward signals'}], answer:'B', explanation:'Unsupervised learning finds patterns in data without labeled responses.' },
  { topic:'AI & ML', difficulty:'Easy',   text:'What does k in k-Nearest Neighbors represent?', options:[{label:'A',text:'Number of clusters'},{label:'B',text:'Number of nearest neighbors to consider'},{label:'C',text:'Learning rate'},{label:'D',text:'Number of features'}], answer:'B', explanation:'k is the number of nearest data points used for classification.' },
  { topic:'AI & ML', difficulty:'Easy',   text:'Which metric measures the proportion of correctly classified instances?', options:[{label:'A',text:'Precision'},{label:'B',text:'Recall'},{label:'C',text:'Accuracy'},{label:'D',text:'F1 Score'}], answer:'C', explanation:'Accuracy = (correct predictions) / (total predictions).' },
  { topic:'AI & ML', difficulty:'Easy',   text:'What is reinforcement learning?', options:[{label:'A',text:'Learning from labeled examples'},{label:'B',text:'Learning from unlabeled data'},{label:'C',text:'Learning by receiving rewards or penalties from an environment'},{label:'D',text:'Learning using pre-trained models'}], answer:'C', explanation:'RL agents learn by taking actions and receiving reward signals.' },
  { topic:'AI & ML', difficulty:'Medium', text:'What does the activation function do in a neural network?', options:[{label:'A',text:'Initializes weights'},{label:'B',text:'Introduces non-linearity into the model'},{label:'C',text:'Normalizes input data'},{label:'D',text:'Calculates the loss'}], answer:'B', explanation:'Activation functions add non-linearity enabling complex pattern learning.' },
  { topic:'AI & ML', difficulty:'Medium', text:'What is overfitting in machine learning?', options:[{label:'A',text:'Model performs well on test data but not training data'},{label:'B',text:'Model performs well on training data but poorly on unseen data'},{label:'C',text:'Model has too few parameters'},{label:'D',text:'Model trains too slowly'}], answer:'B', explanation:'Overfitting means the model memorizes training data but fails to generalize.' },
  { topic:'AI & ML', difficulty:'Medium', text:'What is the purpose of the learning rate in gradient descent?', options:[{label:'A',text:'Number of training epochs'},{label:'B',text:'Controls the step size for updating model weights'},{label:'C',text:'Ratio of training to test data'},{label:'D',text:'Number of hidden layers'}], answer:'B', explanation:'Learning rate determines how large each weight update step is.' },
  { topic:'AI & ML', difficulty:'Medium', text:'What is cross-validation used for?', options:[{label:'A',text:'Speeding up training'},{label:'B',text:'Evaluating model performance on different data splits'},{label:'C',text:'Increasing model complexity'},{label:'D',text:'Reducing the number of features'}], answer:'B', explanation:'Cross-validation estimates model generalization by rotating train/test splits.' },
  { topic:'AI & ML', difficulty:'Medium', text:'What is the purpose of dropout in neural networks?', options:[{label:'A',text:'Speed up training'},{label:'B',text:'Reduce overfitting by randomly deactivating neurons during training'},{label:'C',text:'Initialize weights to zero'},{label:'D',text:'Increase model depth'}], answer:'B', explanation:'Dropout randomly drops neurons during training as a regularization technique.' },
  { topic:'AI & ML', difficulty:'Medium', text:'What is a confusion matrix?', options:[{label:'A',text:'A matrix of model weights'},{label:'B',text:'A table showing predicted vs actual classifications'},{label:'C',text:'A grid of hyperparameters'},{label:'D',text:'A visualization of decision boundaries'}], answer:'B', explanation:'Confusion matrix shows TP, TN, FP, FN for evaluating classifiers.' },
  { topic:'AI & ML', difficulty:'Medium', text:'What does PCA stand for and what is it used for?', options:[{label:'A',text:'Predictive Classification Algorithm; for labeling'},{label:'B',text:'Principal Component Analysis; for dimensionality reduction'},{label:'C',text:'Partial Correlation Analysis; for feature selection'},{label:'D',text:'Probabilistic Clustering Algorithm; for grouping'}], answer:'B', explanation:'PCA reduces dimensionality by projecting data onto principal components.' },
  { topic:'AI & ML', difficulty:'Hard',   text:'What is the vanishing gradient problem?', options:[{label:'A',text:'Gradients become too large during backpropagation'},{label:'B',text:'Gradients become extremely small slowing learning in early layers'},{label:'C',text:'The model loses its training data'},{label:'D',text:'Weights are initialized to zero'}], answer:'B', explanation:'In deep networks gradients shrink exponentially through layers slowing training.' },
  { topic:'AI & ML', difficulty:'Hard',   text:'What is the attention mechanism in transformers?', options:[{label:'A',text:'A regularization technique'},{label:'B',text:'A mechanism that weighs importance of different input positions for each output'},{label:'C',text:'A type of activation function'},{label:'D',text:'A method for weight initialization'}], answer:'B', explanation:'Attention computes weighted relevance of all input positions for each output token.' },
  { topic:'AI & ML', difficulty:'Hard',   text:'What is the bias-variance tradeoff?', options:[{label:'A',text:'Tradeoff between training speed and accuracy'},{label:'B',text:'High bias = underfitting; high variance = overfitting; need to balance both'},{label:'C',text:'Tradeoff between number of features and samples'},{label:'D',text:'Tradeoff between precision and recall'}], answer:'B', explanation:'Bias measures underfitting; variance measures sensitivity to training data.' },
  { topic:'AI & ML', difficulty:'Hard',   text:'What is batch normalization?', options:[{label:'A',text:'Normalizing the input dataset'},{label:'B',text:'Normalizing layer inputs to stabilize and speed up training'},{label:'C',text:'Splitting data into batches'},{label:'D',text:'A type of regularization like dropout'}], answer:'B', explanation:'Batch norm normalizes activations per mini-batch reducing internal covariate shift.' },
  { topic:'AI & ML', difficulty:'Hard',   text:'What is the difference between bagging and boosting?', options:[{label:'A',text:'No difference'},{label:'B',text:'Bagging trains models in parallel on random subsets; boosting trains sequentially fixing errors'},{label:'C',text:'Boosting uses random forests; bagging uses gradient boosting'},{label:'D',text:'Bagging is for regression only; boosting is for classification'}], answer:'B', explanation:'Bagging reduces variance (e.g. Random Forest); boosting reduces bias (e.g. XGBoost).' },
  { topic:'AI & ML', difficulty:'Hard',   text:'What is the role of the loss function in machine learning?', options:[{label:'A',text:'Initialize model weights'},{label:'B',text:'Measure the difference between predicted and actual output to guide training'},{label:'C',text:'Split data into train and test sets'},{label:'D',text:'Select the best features'}], answer:'B', explanation:'Loss function quantifies prediction error; minimizing it improves the model.' },
  { topic:'AI & ML', difficulty:'Hard',   text:'What is transfer learning?', options:[{label:'A',text:'Moving a model from one computer to another'},{label:'B',text:'Reusing a pre-trained model on a new but related task'},{label:'C',text:'Training two models simultaneously'},{label:'D',text:'Converting a model from one framework to another'}], answer:'B', explanation:'Transfer learning leverages knowledge from one task to improve learning on another.' },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    let seedUser = await User.findOne({ email: 'seed@prepmate.com' });
    if (!seedUser) {
      seedUser = await User.create({
        name: 'PrepMate Admin',
        email: 'seed@prepmate.com',
        password: 'seed1234',
        role: 'admin',
      });
      console.log('✅ Seed user created');
    }

    await Question.deleteMany({});
    console.log('🗑️  Cleared existing questions');

    const toInsert = questions.map((q) => ({ ...q, createdBy: seedUser._id, isApproved: true }));
    await Question.insertMany(toInsert);

    const counts = {};
    toInsert.forEach((q) => { counts[q.topic] = (counts[q.topic] || 0) + 1; });
    console.log('\n📚 Questions inserted per topic:');
    Object.entries(counts).forEach(([topic, count]) => console.log(`   ${topic}: ${count}`));
    console.log(`\n✅ Total: ${toInsert.length} questions`);

    await mongoose.disconnect();
    console.log('🎉 Seeding complete! You can now take quizzes.');
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seed();